'use client'


export const dynamic = 'force-dynamic';

import Image from 'next/image'
import Link from 'next/link'
import SectionTitleEle from '../components/ui/SectionTitleEle'
import { PlayersGridSkeleton } from '../components/skeletons/PageSkeletons'
import { useEffect, useState } from 'react'
// Roster now comes from the local DB (Neon) via /api/players (CCC's squad), shaped
// like the old CMS player payload. The "Show Full Stats" modal still uses the live
// CricClubs career stats via /api/player-stats.

// ------------------------------------
// Define interfaces for typed data
// ------------------------------------
interface PlayerImage {
  url: string
  alt?: string
}

interface Player {
  id: string
  title?: string
  country?: string
  teamName?: string
  // This is an array of images, each containing "url" and possibly "alt"
  playerImage?: PlayerImage[]
  nationalFlag?: PlayerImage[]
  jerseyNumber?: number
  matches?: number
  totalruns?: number
  wickets?: number
  scorebycaptain?: number
  playerid?: number
}



// GraphQL response for players
interface GraphQLPlayersResponse {
  entries: Player[]
}

// GraphQL response for configuration
interface PlayerConfigurationResponse {
  globalSet?: {
    lightswitch?: boolean
  }
}

/* ================= TYPES ================= */

interface BattingStat {
  seriesType: string;
  matches: number;
  innings: number;
  runsScored: number;
  highestScore: number;
  average: string;
  strikeRate: string;
  fours: number;
  sixers: number;
  fifties: number;
  hundreds: number;
}

interface BowlingStat {
  seriesType: string;
  matches: number;
  innings: number;
  overs: number | null;
  runsGiven: number;
  wickets: number;
  economy: string;
  maidens: number;
}

interface PlayerStats {
  battingStats: BattingStat[];
  bowlingStats: BowlingStat[];
}



function getFullImageUrl(url: string) {
  const cmsBaseUrl = process.env.NEXT_PUBLIC_CMS_URL || 'http://cms.ccc.clubcricketofchicago.com/'
  if (url?.startsWith('http')) return url
  const cleanUrl = url?.startsWith('/') ? url.substring(1) : url
  const baseUrl = cmsBaseUrl.endsWith('/') ? cmsBaseUrl : `${cmsBaseUrl}/`
  return `${baseUrl}${cleanUrl}`
}

function PlayerCardEle({
  player,
  lightswitch,
  rank,
}: {
  player: Player
  lightswitch: boolean
  rank?: number
}) {
  const playerImage = player.playerImage?.[0]
  const countryAbbreviation = player.country?.toLowerCase()
  const flagUrl = countryAbbreviation
    ? `/images/nationality/${countryAbbreviation}.svg`
    : '/images/sample_flag.png'

  // Face-centered square crop generated by the OpenCV DNN face detector
  // (scratchpad/face/*.py → public/images/players/faces). Falls back to the sample.
  const faceFile = playerImage?.url
    ? playerImage.url.split('/').pop()?.split('?')[0]
    : null
  const profilePic = faceFile
    ? `/images/players/faces/${faceFile}`
    : '/images/sample_player_image.png'

  // Subtle rank cue: a thin top accent bar. Rank 1 is highlighted with the
  // brand orange; everyone else gets a neutral hairline accent.
  const accentColor =
    rank === 1 ? 'var(--orange)' : 'var(--panel-line-strong)'

  interface ApiError {
    error: string;
  }



  const [playerId, setPlayerId] = useState<number | null>(null);

  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [stats, setStats] = useState<PlayerStats>({
    battingStats: [],
    bowlingStats: [],
  });

  const fetchStats = async (id: number) => {
    try {
      setLoading(true);
      setError(null);

      const res = await fetch(
        `/api/player-stats?playerId=${id}`
      );

      const data = await res.json();

      setStats(
        data.data ?? { battingStats: [], bowlingStats: [] }
      );

      setIsOpen(true);
    } catch (err) {
      setError("Failed to fetch stats");
    } finally {
      setLoading(false);
    }
  };

  const openModal = (id: number) => {
    setPlayerId(id);
    fetchStats(id);
  };


  return (
    <div className="playerCardEle relative ccc-card ccc-card-hover overflow-hidden">
      {/* Rank cue: thin top accent bar (orange for #1, neutral otherwise) */}
      <div
        className="absolute top-0 left-0 right-0 h-[3px] z-10"
        style={{ background: accentColor }}
      />
      {/* Top half: player background */}
      <div className="relative w-full aspect-square bg-[var(--panel-2)] overflow-hidden">
        {/* face-centered crop (already squared on the detected face) */}
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: `url(${profilePic})` }}
        />
        {/* flag badge, top-left */}
        <div className="absolute top-[6%] left-[6%] w-[24%] lg:w-[19%] rounded-[3px] overflow-hidden border border-[var(--panel-line-strong)] leading-none">
          <Image
            src={flagUrl}
            alt={player.nationalFlag?.[0]?.alt || ''}
            width={46}
            height={31}
            className="w-full h-auto block"
            unoptimized
          />
        </div>
      </div>
      <div className='grid grid-cols-1 justify-center items-center py-[0.5vw] gap-2 border-y border-[var(--panel-line)]'>
        <div >
          <div >

            {/* Link to full player profile */}
            <Link
              href={`/players/${player.playerid || 0}`}
              className="block text-[color:var(--orange)] font-bold text-center uppercase hover:text-[color:var(--orange-bright)] transition-colors"
            >
              View Profile
            </Link>

            {/* Popup Modal */}
            {isOpen && (
              <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                <div className="ccc-stats-modal w-[900px] max-h-[80vh] overflow-auto rounded-xl p-6 relative shadow-xl">

                  <button
                    onClick={() => setIsOpen(false)}
                    className="absolute top-3 right-4 text-lg"
                  >
                    ✕
                  </button>

                  <h2 className="text-2xl font-bold mb-6">
                    Player Statistics
                  </h2>

                  {loading && <p>Loading...</p>}
                  {error && <p className="text-[color:var(--loss)]">{error}</p>}

                  {!loading &&
                    stats.battingStats.length > 0 && (

                      <div className="space-y-10">

                        {[...new Set(
                          stats.battingStats.map(b => b.seriesType)
                        )].map((type) => {

                          const battingByType =
                            stats.battingStats.filter(
                              (b) => b.seriesType === type
                            );

                          const bowlingByType =
                            stats.bowlingStats.filter(
                              (b) => b.seriesType === type
                            );

                          return (
                            <div key={type} className="space-y-6">

                              <h3 className="text-xl font-semibold border-b pb-2">
                                {type} Stats
                              </h3>

                              {/* Batting Table */}
                              {battingByType.length > 0 && (
                                <div className="overflow-auto border rounded-lg">
                                  <table className="min-w-full text-sm">
                                    <thead className="bg-gray-100">
                                      <tr>
                                        <th className="border px-3 py-2">Matches</th>
                                        <th className="border px-3 py-2">Runs</th>
                                        <th className="border px-3 py-2">Highest</th>
                                        <th className="border px-3 py-2">Avg</th>
                                        <th className="border px-3 py-2">SR</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {battingByType.map((bat, i) => (
                                        <tr key={i} className="text-center">
                                          <td className="border px-3 py-2">
                                            {bat.matches}
                                          </td>
                                          <td className="border px-3 py-2 font-semibold">
                                            {bat.runsScored}
                                          </td>
                                          <td className="border px-3 py-2">
                                            {bat.highestScore}
                                          </td>
                                          <td className="border px-3 py-2">
                                            {bat.average}
                                          </td>
                                          <td className="border px-3 py-2">
                                            {bat.strikeRate}
                                          </td>
                                        </tr>
                                      ))}
                                    </tbody>
                                  </table>
                                </div>
                              )}

                              {/* Bowling Table */}
                              {bowlingByType.length > 0 && (
                                <div className="overflow-auto border rounded-lg">
                                  <table className="min-w-full text-sm">
                                    <thead className="bg-gray-100">
                                      <tr>
                                        <th className="border px-3 py-2">Matches</th>
                                        <th className="border px-3 py-2">Wickets</th>
                                        <th className="border px-3 py-2">Runs</th>
                                        <th className="border px-3 py-2">Economy</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {bowlingByType.map((bowl, i) => (
                                        <tr key={i} className="text-center">
                                          <td className="border px-3 py-2">
                                            {bowl.matches}
                                          </td>
                                          <td className="border px-3 py-2 font-semibold">
                                            {bowl.wickets}
                                          </td>
                                          <td className="border px-3 py-2">
                                            {bowl.runsGiven}
                                          </td>
                                          <td className="border px-3 py-2">
                                            {bowl.economy}
                                          </td>
                                        </tr>
                                      ))}
                                    </tbody>
                                  </table>
                                </div>
                              )}

                            </div>
                          );
                        })}

                      </div>
                    )}

                </div>
              </div>
            )}
          </div>
        </div>


      </div>
      {/* Bottom: name + readable 3-column stats */}
      <div className="aspect-[284/228] h-auto flex">
        <div className="playerMainInfo w-[92%] mx-auto h-full flex flex-col justify-center py-[5%]">
          <h2 className="text-center roboto-condensed-bold text-[4.6vw] lg:text-[1.15vw] leading-tight text-[color:var(--text)] uppercase truncate">
            {player.title}
          </h2>

          {lightswitch ? (
            // Show jersey number
            <div className="jerInfo flex h-[56%] w-full">
              <h5 className="my-auto roboto-condensed-bold text-[8vw] lg:text-[2.8vw] text-[color:var(--orange)] m-auto">
                {player.jerseyNumber}
              </h5>
            </div>
          ) : (
            // Show stats — big number over small label, 3 columns
            <div className="grid grid-cols-3 mt-[8%]">
              <div className="text-center px-[2%]">
                <p className="ds-num text-[6.2vw] lg:text-[1.6vw] leading-none text-[color:var(--text)]">{player.matches ?? 0}</p>
                <p className="roboto-condensed-med text-[2.7vw] lg:text-[0.66vw] tracking-[0.12em] mt-[14%] text-[color:var(--text-muted)] uppercase">Matches</p>
              </div>
              <div className="text-center px-[2%] border-x border-[var(--panel-line)]">
                <p className="ds-num text-[6.2vw] lg:text-[1.6vw] leading-none text-[color:var(--orange)]">{player.totalruns ?? 0}</p>
                <p className="roboto-condensed-med text-[2.7vw] lg:text-[0.66vw] tracking-[0.12em] mt-[14%] text-[color:var(--text-muted)] uppercase">Runs</p>
              </div>
              <div className="text-center px-[2%]">
                <p className="ds-num text-[6.2vw] lg:text-[1.6vw] leading-none text-[color:var(--text)]">{player.wickets ?? 0}</p>
                <p className="roboto-condensed-med text-[2.7vw] lg:text-[0.66vw] tracking-[0.12em] mt-[14%] text-[color:var(--text-muted)] uppercase">Wickets</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default function Page() {
  // 1) Type your state for players
  const [players, setPlayers] = useState<Player[]>([])

  // 2) Type your configuration value (lightswitch: boolean)
  const [lightswitch, setLightswitch] = useState<boolean>(false)
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch('/api/players')
        const playersData: GraphQLPlayersResponse = await res.json()

        if (playersData && playersData.entries) {
          setPlayers(playersData.entries)
        } else {
          throw new Error('No player data returned from API')
        }

        // Show stats (matches/runs/wickets) for everyone, uniformly.
        setLightswitch(false)
      } catch (err) {
        console.error('Error fetching data:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [])

  return (
    <section className="allPlayersPanel_header lg:base_paddings">
      <div className="LSC_parent PlayersPage center_aligned px-[3.5%] pb-[20%] pt-[10%] lg:py-[2%] bg-white/10 backdrop-blur-sm rounded-[2vw] lg:pb-[6vw]">
        <SectionTitleEle>Players</SectionTitleEle>
        <hr className="w-full h-[0.1vw] bg-[#FFFFFF] border-none" />
        <div className="players_panel_container items-center relative">
          {loading ? (
            <PlayersGridSkeleton count={12} />
          ) : (
            players.map((player, index) => (
              <PlayerCardEle key={player.id} player={player} lightswitch={lightswitch} rank={index + 1} />
            ))
          )}

        </div>
      </div>
    </section>
  )
}

// --------------------------------------
// Additional types used in data fetches
// --------------------------------------
interface GraphQLPlayersResponse {
  entries: Player[]
}

interface PlayerConfigurationResponse {
  globalSet?: {
    lightswitch?: boolean
  }
}
